sudo: required
services:
  - docker
language: python
cache: pip
python:
  - "2.7"
install:
  - pip install nose mock docker-py testinfra
  - pip install pytest
  - python setup.py install
script:
  - nosetests --nologcapture --cover-package=tocker
