sudo: required
services:
  - docker
language: python
cache: pip
python:
  - "2.7"
install:
  - pip install nose mock docker-py testinfra
  - pip install -U pytest==2.9.1
  - python setup.py install
script:
  - nosetests --nologcapture --cover-package=tocker
  - cd examples/nginx && testinfra test.py -v
  - docker ps -a
  - docker images

